os: linux
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6
env:
  - CC=clang-3.6
  - CXX=clang++-3.6
script:
  - cd build
  - cmake ..
  - make
  - ctest
