language: cpp
compiler: clang
addons:
  apt:
    sources:
      - llvm-toolchain-precise
    packages:
      - clang-3.6
install:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script:
  - cd build
  - cmake ..
  - make
  - ctest
