language: cpp
compiler: clang
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6
install:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
script:
  - cd build
  - cmake ..
  - make
  - ctest
